name: Generar documentació Pydoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instal·lar Django
        run: |
          pip install django

      - name: Crear carpeta docs
        run: mkdir -p docs

      - name: Executar script de documentació
        run: |
          python gen-docs.py
          mv *.html docs/

      - name: Copiar CSS
        run: |
          cp style.css docs/

      - name: Publicar GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs